name: bulebule
channels:
  - conda-forge
  - dlr-sc
  - oce
  - pythonocc
  - tpaviot
dependencies:
  - python=3.6
  - pythonocc-core=0.18.2
  - pip:
    - git+https://github.com/CadQuery/cadquery.git@master#egg=cadquery
    - cffi
    - dataclasses
    - osbrain
    - matplotlib
    - mmsim
    - notebook
    - numpy
    - pandas
    #- pybluez
    - pyqt5
    - pyqtgraph
    - pyserial
    - pyzmq
    # Test
    - pytest
    # Lint
    - flake8
    - flake8-quotes
    # Documentation
    - doc8
    - sphinx
    - sphinxcadquery
    - sphinxembeddedvideos
    - sphinxemoji
    # Development
    - pdbpp
